format = """
[░▒▓](#ffd033)\
[ 󱔎 ](bg:#ffd000 fg:#252525)\
[󰇝](bg:#ffd000 fg:#161616)\
$directory\
[](fg:#ffd000 bg:#323232)\
$git_branch\
$git_status\
[](fg:#323232 bg:#202020)\
$nodejs\
$rust\
$golang\
$c\
[](fg:#222222 bg:#161616)\
$time\
[ ](fg:#161616)\
\n$character"""

[directory]
style = "fg:#252525 bg:#ffd000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#FFF692"
format = '[[ $symbol $branch ](fg:#FFD000 bg:#323232)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#FFD000 bg:#323232)]($style)'

[nodejs]
symbol = ""
style = "bg:#222222"
format = '[[ $symbol ($version) ](fg:#ffd000 bg:#202020)]($style)'

[rust]
symbol = ""
style = "ffd098"
format = '[[ $symbol ($version) ](fg:#ffd000 bg:#202020)]($style)'

[golang]
symbol = "󰟓"
style = "ffd098"
format = '[[ $symbol ($version) ](fg:#ffd000 bg:#202020)]($style)'

[c]
symbol = ""
style = "ffd098"
format = '[[ $symbol ($version) ](fg:#ffd000 bg:#202020)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#fefefe bg:#161616)]($style)'

[character]
success_symbol = "󰜴"
